### ISSUE TITLE
Feature request: RSS feed

### ISSUE THREAD

**Issue by sumnerevans** [jacobwhall/jacobhall.net#1]
I'd like to follow the blog via RSS.

**Comment by jacobwhall** [comment]
Next on my todo list! Seems only fair since I just followed your feed :grin:

**Comment by jacobwhall** [comment]
Update, I've built a database to hold my posts and created [an experimental h-feed](https://jacobhall.net/entry.php) of my posts. RSS feed is on the horizon!

**Comment by jacobwhall** [comment]
RSS feed in alpha. There are still a couple of [validator](https://validator.w3.org/feed/) errors that I need to resolve. I'll also test my feed in a couple of readers before I announce it is done. Tentative URL is [https://jacobhall.net/feed.php?type=rss](https://jacobhall.net/feed.php?type=rss)

**Comment by jacobwhall** [comment]
I am declaring the RSS feed usable with 60be007. You can now subscribe to my posts using the following link:

https://jacobhall.net/feeds/rss/v1.rss

Please note that I purposefully excluded certain post types such as bookmarks and likes so that the feed would be mostly original content, and to prevent spamming followers. I have plans to allow followers to specify post types that they would like to follow, and to add more embedded multimedia so that you don't have to click through to my site as much to see the main content. The version number will allow me to make major updates to the feed formatting if needed without interrupting the current system.

Please let me know if you have any feedback!

**Comment by sumnerevans** [comment]
Looks good! It's working in my feed reader.
